### ISSUE TITLE
change color after install 

### ISSUE THREAD

**Issue by ShanLing-cool** [ris58h/WebCalm#11]
After I install this plug-in, the script tag will turn green, and it will look strange if the code in IDEA matches with the black theme. Is there any way to keep the primary color?
![image](https://github.com/ris58h/WebCalm/assets/62042194/9a271360-e4c6-4104-b66a-578de113ff21)

**Comment by ris58h** [comment]
This is how IntelliJ highlights injected code. Maybe this links will help you:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206847725

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206315049

**Comment by ShanLing-cool** [comment]
Thank you for your answer, I have solved the problem
