### ISSUE TITLE
After restart idea, TextMate color scheme (e.g. html file) not work.

### ISSUE THREAD

**Issue by PassingByThs** [ris58h/WebCalm#19]
IDEA Version: 
![图片](https://github.com/ris58h/WebCalm/assets/48084783/5a7de343-05ea-44ec-8233-17547d9396a1)

I  disabled WebCalm plugin.
![图片](https://github.com/ris58h/WebCalm/assets/48084783/5beab378-1aa4-45d3-af46-cf79e7c88af7)

HTML file type still exist, it seems no problem. 
![图片](https://github.com/ris58h/WebCalm/assets/48084783/7fe884e4-81eb-4087-8f9b-8ccad41eb960)

As we can see above , *.html not included.
test.html is not colored.
![图片](https://github.com/ris58h/WebCalm/assets/48084783/2034d23a-5126-4e66-921e-d9fb9d31bf85)

Add *.html to HTML file type. 
![图片](https://github.com/ris58h/WebCalm/assets/48084783/15c3adf5-5119-4426-911d-6b3730b3b75b)
Click Reassign Wildcard and Apply
![图片](https://github.com/ris58h/WebCalm/assets/48084783/919591bc-0859-43fa-97f2-ef83e9c353f1)

test.html is colored by HTML file type.
![图片](https://github.com/ris58h/WebCalm/assets/48084783/32a09359-da01-4521-aeea-791b87097fec)

Remove *.html to HTML file type.
![图片](https://github.com/ris58h/WebCalm/assets/48084783/72a92336-6d4b-4126-8281-bc91c00e7686)
![图片](https://github.com/ris58h/WebCalm/assets/48084783/e97b7fba-345c-4be2-97da-a7f3d7890b60)

test.html is colored by TextMate. [More info about TextMate](https://www.jetbrains.com/help/idea/textmate.html)
![图片](https://github.com/ris58h/WebCalm/assets/48084783/162f1c84-7d49-40b0-867c-6a73bdfb2c58)

Close IDEA and restart.
test.html is not colored.
![图片](https://github.com/ris58h/WebCalm/assets/48084783/11e612cc-5971-4224-9df5-c946260e5446)
![图片](https://github.com/ris58h/WebCalm/assets/48084783/734f5600-66f2-4329-b8e3-f8579daec756)

**Comment by ris58h** [comment]
Hi!

WebCalm doesn't do anything with HTML highlighting. It just injects JS/CSS into HTML.

If there is an issue with HTML highlighting you should report it to JetBrains https://youtrack.jetbrains.com/
